spring:
  application:
    name: notification-service

server:
  port: 8082

spring:
  mail:
    host: ${SMTP_HOST:mailhog}
    port: ${SMTP_PORT:1025}
    username: ${SMTP_USER:}
    password: ${SMTP_PASS:}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      mailService:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
