spring:
  application:
    name: user-service

server:
  port: 8081

datasource:
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/user_db
    username: postgres
    password: Kemmill12_
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
